export const content = [
    {
        id: 0,
        title: "Randomdash",
        time: "1h ago",
        type: "comment",
        avatar: "/images/avatars/3.png",
        details: "Classic Car in Studio",
        content:
            "These draggabale sliders look really cool. Maybe these could be displayed when you hold shift, to rotate exactly on the X or Y. But by default I don't think we need these controllers, you could just rotate the object by clicking and dragging anywhere as expected on any 3D tool (theoretically).",
        new: true,
    },
    {
        id: 1,
        title: "Cute Turtle is generated",
        time: "2h ago",
        type: "image",
        avatar: "/images/avatars/1.png",
        details: "Matte texture - UI8 Style",
        content: "Prompt: Create 3D character dancing",
        new: true,
    },
    {
        id: 2,
        title: "3D object is generated",
        time: "4h ago",
        type: "invite",
        avatar: "/images/avatars/4.png",
        details: "Minimalist Architecture Scene",
        new: true,
    },
    {
        id: 3,
        title: "Marina",
        time: "10h ago",
        type: "like",
        avatar: "/images/avatars/5.png",
        details: "Classic Car in Studio",
        new: false,
    },
    {
        id: 4,
        title: "3D object is generated",
        time: "16h ago",
        type: "comment",
        avatar: "/images/avatars/2.png",
        details: "Classic Car in Studio",
        content:
            "These draggabale sliders look really cool. Maybe these could be displayed when you hold shift, to rotate exactly on the X or Y. But by default I don't think we need these controllers, you could just rotate the object by clicking and dragging anywhere as expected on any 3D tool (theoretically).",
        new: false,
    },
    {
        id: 5,
        title: "Animation is generated",
        time: "1d ago",
        type: "video",
        avatar: "/images/avatars/1.png",
        details: "12s – 720p",
        content: "Prompt: Create 3D character dancing",
        new: false,
    },
    {
        id: 6,
        title: "Randomdash",
        time: "1h ago",
        type: "comment",
        avatar: "/images/avatars/3.png",
        details: "Classic Car in Studio",
        content:
            "These draggabale sliders look really cool. Maybe these could be displayed when you hold shift, to rotate exactly on the X or Y. But by default I don't think we need these controllers, you could just rotate the object by clicking and dragging anywhere as expected on any 3D tool (theoretically).",
        new: true,
    },
    {
        id: 7,
        title: "Cute Turtle is generated",
        time: "2h ago",
        type: "image",
        avatar: "/images/avatars/1.png",
        details: "Matte texture - UI8 Style",
        content: "Prompt: Create 3D character dancing",
        new: true,
    },
];
